### ISSUE TITLE
Demo Project - Internal 500 Error

### ISSUE THREAD

**Issue by rodydavis** [TwilioDevEd/clicktocall-csharp#12]
After setting the correct "TwilioAccountSID" , "TwilioAuthToken" , and "TwilioNumber" the web page says "There was a problem calling you - please try again later." I can use other Twilio functions in other apps but the ClickToCall is not working. It will not dial out to either number.

![image](https://user-images.githubusercontent.com/31253215/29578478-6a953630-873d-11e7-8a6e-a329ffde4f64.png)

Log:
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery-1.10.2.js:5375:28
XML Parsing Error: no root element found
Location: http://localhost:57471/01d55b0057f14d8aa4f39e67f234bae7/browserLinkSignalR/abort?transport=webSockets&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAA9nnpT%2Bd2GEGGBvJN2iSr%2FAAAAAACAAAAAAAQZgAAAAEAACAAAAA5C0avgoOxzy0g8wtuZzNLaBQla80xMib%2FzC%2Ft9UuALwAAAAAOgAAAAAIAACAAAAAVgVKnWONXBwpQ%2FQynRYyeKOOZw8ZnvXuTf7SIoOTAGDAAAAD7kYmTiT%2FoNJJMIKh5KrXfhkyBndCsBDP4QnpepbcwWc6o30MXPHYCyAiJwt2Dy2pAAAAAQWB%2BSLeKghpSzeaKqUHL7LVhQ8%2FfLiCtjRL9V%2BL03xElOpifAfuaJ2NzMxckwj2z3BoQ%2BCb7lW9A6zBQMPSXGQ%3D%3D&requestUrl=http%3A%2F%2Flocalhost%3A1430%2F&browserName=Firefox&userAgent=Mozilla%2F5.0+(Windows+NT+10.0%3B+WOW64%3B+rv%3A54.0)+Gecko%2F20100101+Firefox%2F54.0
Line Number 1, Column 1:  abort:1:1
POST 
XHR 
http://localhost:1430/CallCenter/Call [HTTP/1.1 500 Internal Server Error 18ms]
Headers
POST
Response
Call Stack
Cache-ControlprivateContent-Length12174Content-Typetext/html; charset=utf-8DateTue, 22 Aug 2017 17:26:58 GMTServerMicrosoft-IIS/10.0X-AspNet-Version4.0.30319X-Powered-ByASP.NETX-SourceFiles=?UTF-8?B?QzpcVXNlcnNcUmhvZGVzXERvd25sb2Fkc1xjbGlja3RvY2FsbC1jc2hhcnAtbWFzdGVyICgxKVxjbGlja3RvY2FsbC1jc2hhcnAtbWFzdGVyXENsaWNrVG9DYWxsLldlYlxDYWxsQ2VudGVyXENhbGw=?=
Acceptapplication/json, text/javascript, */*; q=0.01Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5Connectionkeep-aliveContent-Length52Content-Typeapplication/x-www-form-urlencoded; charset=UTF-8Hostlocalhost:1430Refererhttp://localhost:1430/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0X-Requested-WithXMLHttpRequest

**Comment by rodydavis** [comment]
https://stackoverflow.com/questions/45824258/twilio-clicktocall-csharp-internal-500-error-after-first-launch

**Comment by rodydavis** [comment]
![tunnel](https://user-images.githubusercontent.com/31253215/29725631-cbd047c8-899a-11e7-857e-6891680b8e85.JPG)

**Comment by dprothero** [comment]
Thanks for the bug report. I've just pushed up a fix.

**Comment by rodydavis** [comment]
No Problem, thanks for the fix!
